#ifdef RELOAD_TABLE_COMMAND
    RELOAD_TABLE_COMMAND("creature_template",                sObjectMgr.LoadCreatureTemplates,        HandleReloadCreatureTemplate)
    RELOAD_TABLE_COMMAND("item_template",                    sObjectMgr.LoadItemPrototypes,           HandleReloadItemTemplate)
    RELOAD_TABLE_COMMAND("instance_template",                sObjectMgr.LoadInstanceTemplate,         HandleReloadInstanceTemplate)
    RELOAD_TABLE_COMMAND("world_template",                   sObjectMgr.LoadWorldTemplate,            HandleReloadWorldTemplate)
    RELOAD_TABLE_COMMAND("gameobject_template",              sObjectMgr.LoadGameobjectInfo,           HandleReloadGameObjectTemplate)
    RELOAD_TABLE_COMMAND("exploration_basexp",               sObjectMgr.LoadExplorationBaseXP,        HandleReloadExplorationBaseXp)
    RELOAD_TABLE_COMMAND("pet_name_generation",              sObjectMgr.LoadPetNames,                 HandleReloadPetNameGeneration)
    RELOAD_TABLE_COMMAND("creature_onkill_reputation",       sObjectMgr.LoadReputationOnKill,         HandleReloadCreatureOnKillReputation)
    RELOAD_TABLE_COMMAND("game_weather",                     sObjectMgr.LoadWeatherZoneChances,       HandleReloadGameWeather)
    RELOAD_TABLE_COMMAND("player_factionchange_reputations", sObjectMgr.LoadFactionChangeReputations, HandleReloadFactionChangeReputations)
    RELOAD_TABLE_COMMAND("player_factionchange_spells",      sObjectMgr.LoadFactionChangeSpells,      HandleReloadFactionChangeSpells)
    RELOAD_TABLE_COMMAND("player_factionchange_items",       sObjectMgr.LoadFactionChangeItems,       HandleReloadFactionChangeItems)
    RELOAD_TABLE_COMMAND("player_factionchange_quests",      sObjectMgr.LoadFactionChangeQuests,      HandleReloadFactionChangeQuests)
    RELOAD_TABLE_COMMAND("player_factionchange_mounts",      sObjectMgr.LoadFactionChangeMounts,      HandleReloadFactionChangeMounts)
    RELOAD_TABLE_COMMAND("creature_model_info",              sObjectMgr.LoadCreatureModelInfo,        HandleReloadCreatureModelInfo)
    RELOAD_TABLE_COMMAND("elysium_string",                   sObjectMgr.LoadElysiumStrings,           HandleReloadElysiumStrings)
    RELOAD_TABLE_COMMAND("ip_banned",                        sAccountMgr.LoadIPBanList,               HandleReloadIPBanList)
    RELOAD_TABLE_COMMAND("account_banned",                   sAccountMgr.LoadAccountBanList,          HandleReloadAccountBanList)
#endif
